// GENERATED by tools/kit-table.py from payload/mods/collision-guard/tests/register.test.ts: do not edit; run the tool.
//
// Every answer the collision guard's tests take from their table of mod-kit answers, asked of
// mod-kit's real reader (#760 item 7). An entry failing here means the reader has moved and the
// collision guard's tests are green against an answer it no longer gives: re-measure that entry
// in the table, then run the tool again.
import { describe, expect, test } from 'claude-code/testing'
import { commands, git } from '../hooks/commands.ts'
import { commandWrites } from '../hooks/writes.ts'

type Entry = { method: 'commands' | 'writes' | 'git'; input: Record<string, unknown>; want: unknown }
const ENTRIES: Entry[] = [
  {"method":"commands","input":{"command":"echo x > unwritable.txt; echo y > fine.txt"},"want":[["echo","x",">","unwritable.txt"],["echo","y",">","fine.txt"]]},
  {"method":"git","input":{"words":["echo","x",">","unwritable.txt"]},"want":null},
  {"method":"git","input":{"words":["echo","y",">","fine.txt"]},"want":null},
  {"method":"writes","input":{"command":"echo x > unwritable.txt; echo y > fine.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"unwritable.txt","path":"/repo/unwritable.txt"},{"word":"fine.txt","path":"/repo/fine.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"git checkout main"},"want":[["git","checkout","main"]]},
  {"method":"git","input":{"words":["git","checkout","main"]},"want":{"sub":"checkout","args":["main"]}},
  {"method":"writes","input":{"command":"git checkout main","cwd":"/repo","home":""},"want":{"files":[],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"git -C /other reset --hard origin/main"},"want":[["git","-C","/other","reset","--hard","origin/main"]]},
  {"method":"git","input":{"words":["git","-C","/other","reset","--hard","origin/main"]},"want":{"sub":"reset","args":["--hard","origin/main"],"dir":"/other"}},
  {"method":"writes","input":{"command":"git -C /other reset --hard origin/main","cwd":"/repo","home":""},"want":{"files":[],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"git status"},"want":[["git","status"]]},
  {"method":"git","input":{"words":["git","status"]},"want":{"sub":"status","args":[]}},
  {"method":"writes","input":{"command":"git status","cwd":"/repo","home":""},"want":{"files":[],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"printf 'one more line\\n' >> notes.txt"},"want":[["printf","one more line\\n",">>","notes.txt"]]},
  {"method":"git","input":{"words":["printf","one more line\\n",">>","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"printf 'one more line\\n' >> notes.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"notes.txt","path":"/repo/notes.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"echo done >> notes.txt"},"want":[["echo","done",">>","notes.txt"]]},
  {"method":"git","input":{"words":["echo","done",">>","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"echo done >> notes.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"notes.txt","path":"/repo/notes.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"printf x >> notes.txt; false"},"want":[["printf","x",">>","notes.txt"],["false"]]},
  {"method":"git","input":{"words":["printf","x",">>","notes.txt"]},"want":null},
  {"method":"git","input":{"words":["false"]},"want":null},
  {"method":"writes","input":{"command":"printf x >> notes.txt; false","cwd":"/repo","home":""},"want":{"files":[{"word":"notes.txt","path":"/repo/notes.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"echo x >> notes.txt"},"want":[["echo","x",">>","notes.txt"]]},
  {"method":"git","input":{"words":["echo","x",">>","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"echo x >> notes.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"notes.txt","path":"/repo/notes.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"sed -i \"\" s/a/b/ notes.txt"},"want":[["sed","-i","","s/a/b/","notes.txt"]]},
  {"method":"git","input":{"words":["sed","-i","","s/a/b/","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"sed -i \"\" s/a/b/ notes.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"notes.txt","path":"/repo/notes.txt","edits":true}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"cat notes.txt"},"want":[["cat","notes.txt"]]},
  {"method":"git","input":{"words":["cat","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"cat notes.txt","cwd":"/repo","home":""},"want":{"files":[],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"python3 -c \"open('notes.txt','a').write('x')\""},"want":[["python3","-c","open('notes.txt','a').write('x')"]]},
  {"method":"git","input":{"words":["python3","-c","open('notes.txt','a').write('x')"]},"want":null},
  {"method":"writes","input":{"command":"python3 -c \"open('notes.txt','a').write('x')\"","cwd":"/repo","home":""},"want":{"files":[],"changes":[],"unnamed":[{"what":"an inline python3 script","words":["python3","-c","open('notes.txt','a').write('x')"],"inputs":[],"targets":["/repo/notes.txt"]}]}},
  {"method":"commands","input":{"command":"cp /tmp/notes.txt docs"},"want":[["cp","/tmp/notes.txt","docs"]]},
  {"method":"git","input":{"words":["cp","/tmp/notes.txt","docs"]},"want":null},
  {"method":"writes","input":{"command":"cp /tmp/notes.txt docs","cwd":"/repo","home":""},"want":{"files":[{"word":"docs","path":"/repo/docs","sources":["/tmp/notes.txt"],"mayBeFolder":true}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"cp /tmp/x.txt notes.txt"},"want":[["cp","/tmp/x.txt","notes.txt"]]},
  {"method":"git","input":{"words":["cp","/tmp/x.txt","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"cp /tmp/x.txt notes.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"notes.txt","path":"/repo/notes.txt","sources":["/tmp/x.txt"],"mayBeFolder":true}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"echo x > notes.txt"},"want":[["echo","x",">","notes.txt"]]},
  {"method":"git","input":{"words":["echo","x",">","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"echo x > notes.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"notes.txt","path":"/repo/notes.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"rm notes.txt"},"want":[["rm","notes.txt"]]},
  {"method":"git","input":{"words":["rm","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"rm notes.txt","cwd":"/repo","home":""},"want":{"files":[],"changes":[{"word":"notes.txt","path":"/repo/notes.txt","does":"remove"}],"unnamed":[]}},
  {"method":"commands","input":{"command":"unlink notes.txt"},"want":[["unlink","notes.txt"]]},
  {"method":"git","input":{"words":["unlink","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"unlink notes.txt","cwd":"/repo","home":""},"want":{"files":[],"changes":[{"word":"notes.txt","path":"/repo/notes.txt","does":"remove"}],"unnamed":[]}},
  {"method":"commands","input":{"command":"rm -f old.txt"},"want":[["rm","-f","old.txt"]]},
  {"method":"git","input":{"words":["rm","-f","old.txt"]},"want":null},
  {"method":"writes","input":{"command":"rm -f old.txt","cwd":"/repo","home":""},"want":{"files":[],"changes":[{"word":"old.txt","path":"/repo/old.txt","does":"remove"}],"unnamed":[]}},
  {"method":"commands","input":{"command":"rm -rf src"},"want":[["rm","-rf","src"]]},
  {"method":"git","input":{"words":["rm","-rf","src"]},"want":null},
  {"method":"writes","input":{"command":"rm -rf src","cwd":"/repo","home":""},"want":{"files":[],"changes":[{"word":"src","path":"/repo/src","does":"remove","tree":true}],"unnamed":[]}},
  {"method":"commands","input":{"command":"mv src /tmp/old-src"},"want":[["mv","src","/tmp/old-src"]]},
  {"method":"git","input":{"words":["mv","src","/tmp/old-src"]},"want":null},
  {"method":"writes","input":{"command":"mv src /tmp/old-src","cwd":"/repo","home":""},"want":{"files":[{"word":"/tmp/old-src","path":"/tmp/old-src","sources":["/repo/src"],"mayBeFolder":true}],"changes":[{"word":"src","path":"/repo/src","does":"remove","tree":true}],"unnamed":[]}},
  {"method":"commands","input":{"command":"cp -r /tmp/sub docs; rm -r docs/sub"},"want":[["cp","-r","/tmp/sub","docs"],["rm","-r","docs/sub"]]},
  {"method":"git","input":{"words":["cp","-r","/tmp/sub","docs"]},"want":null},
  {"method":"git","input":{"words":["rm","-r","docs/sub"]},"want":null},
  {"method":"writes","input":{"command":"cp -r /tmp/sub docs; rm -r docs/sub","cwd":"/repo","home":""},"want":{"files":[{"word":"docs","path":"/repo/docs","sources":["/tmp/sub"],"mayBeFolder":true}],"changes":[{"word":"docs/sub","path":"/repo/docs/sub","does":"remove","tree":true}],"unnamed":[]}},
  {"method":"commands","input":{"command":"cp /tmp/a.ts docs; rm -r docs"},"want":[["cp","/tmp/a.ts","docs"],["rm","-r","docs"]]},
  {"method":"git","input":{"words":["cp","/tmp/a.ts","docs"]},"want":null},
  {"method":"git","input":{"words":["rm","-r","docs"]},"want":null},
  {"method":"writes","input":{"command":"cp /tmp/a.ts docs; rm -r docs","cwd":"/repo","home":""},"want":{"files":[{"word":"docs","path":"/repo/docs","sources":["/tmp/a.ts"],"mayBeFolder":true}],"changes":[{"word":"docs","path":"/repo/docs","does":"remove","tree":true}],"unnamed":[]}},
  {"method":"commands","input":{"command":"echo > d; rm -r d"},"want":[["echo",">","d"],["rm","-r","d"]]},
  {"method":"git","input":{"words":["echo",">","d"]},"want":null},
  {"method":"git","input":{"words":["rm","-r","d"]},"want":null},
  {"method":"writes","input":{"command":"echo > d; rm -r d","cwd":"/repo","home":""},"want":{"files":[{"word":"d","path":"/repo/d"}],"changes":[{"word":"d","path":"/repo/d","does":"remove","tree":true}],"unnamed":[]}},
  {"method":"commands","input":{"command":"rm '/Users/dan/Documents/Documents - Dan\u2019s MacBook Pro/app.ts'"},"want":[["rm","/Users/dan/Documents/Documents - Dan\u2019s MacBook Pro/app.ts"]]},
  {"method":"git","input":{"words":["rm","/Users/dan/Documents/Documents - Dan\u2019s MacBook Pro/app.ts"]},"want":null},
  {"method":"writes","input":{"command":"rm '/Users/dan/Documents/Documents - Dan\u2019s MacBook Pro/app.ts'","cwd":"/repo","home":""},"want":{"files":[],"changes":[{"word":"/Users/dan/Documents/Documents - Dan\u2019s MacBook Pro/app.ts","path":"/Users/dan/Documents/Documents - Dan\u2019s MacBook Pro/app.ts","does":"remove"}],"unnamed":[]}},
  {"method":"commands","input":{"command":"rm -r '/Users/dan/Documents/Documents - Dan\u2019s MacBook Pro'"},"want":[["rm","-r","/Users/dan/Documents/Documents - Dan\u2019s MacBook Pro"]]},
  {"method":"git","input":{"words":["rm","-r","/Users/dan/Documents/Documents - Dan\u2019s MacBook Pro"]},"want":null},
  {"method":"writes","input":{"command":"rm -r '/Users/dan/Documents/Documents - Dan\u2019s MacBook Pro'","cwd":"/repo","home":""},"want":{"files":[],"changes":[{"word":"/Users/dan/Documents/Documents - Dan\u2019s MacBook Pro","path":"/Users/dan/Documents/Documents - Dan\u2019s MacBook Pro","does":"remove","tree":true}],"unnamed":[]}},
  {"method":"commands","input":{"command":"rm -r src/"},"want":[["rm","-r","src/"]]},
  {"method":"git","input":{"words":["rm","-r","src/"]},"want":null},
  {"method":"writes","input":{"command":"rm -r src/","cwd":"/repo","home":""},"want":{"files":[],"changes":[{"word":"src/","path":"/repo/src","does":"remove","tree":true}],"unnamed":[]}},
  {"method":"commands","input":{"command":"rm -r src"},"want":[["rm","-r","src"]]},
  {"method":"git","input":{"words":["rm","-r","src"]},"want":null},
  {"method":"writes","input":{"command":"rm -r src","cwd":"/repo","home":""},"want":{"files":[],"changes":[{"word":"src","path":"/repo/src","does":"remove","tree":true}],"unnamed":[]}},
  {"method":"commands","input":{"command":"echo x > /tmp/out.txt && echo y > /private/tmp/claude-501/s/scratchpad/674/n.md && echo z >> notes.txt"},"want":[["echo","x",">","/tmp/out.txt"],["echo","y",">","/private/tmp/claude-501/s/scratchpad/674/n.md"],["echo","z",">>","notes.txt"]]},
  {"method":"git","input":{"words":["echo","x",">","/tmp/out.txt"]},"want":null},
  {"method":"git","input":{"words":["echo","y",">","/private/tmp/claude-501/s/scratchpad/674/n.md"]},"want":null},
  {"method":"git","input":{"words":["echo","z",">>","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"echo x > /tmp/out.txt && echo y > /private/tmp/claude-501/s/scratchpad/674/n.md && echo z >> notes.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"/tmp/out.txt","path":"/tmp/out.txt"},{"word":"/private/tmp/claude-501/s/scratchpad/674/n.md","path":"/private/tmp/claude-501/s/scratchpad/674/n.md"},{"word":"notes.txt","path":"/repo/notes.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"echo x > /tmp/out.txt; echo z >> notes.txt"},"want":[["echo","x",">","/tmp/out.txt"],["echo","z",">>","notes.txt"]]},
  {"method":"writes","input":{"command":"echo x > /tmp/out.txt; echo z >> notes.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"/tmp/out.txt","path":"/tmp/out.txt"},{"word":"notes.txt","path":"/repo/notes.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"echo x > /tmp/shared.txt"},"want":[["echo","x",">","/tmp/shared.txt"]]},
  {"method":"git","input":{"words":["echo","x",">","/tmp/shared.txt"]},"want":null},
  {"method":"writes","input":{"command":"echo x > /tmp/shared.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"/tmp/shared.txt","path":"/tmp/shared.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"echo x >> /wt/feature/notes.txt"},"want":[["echo","x",">>","/wt/feature/notes.txt"]]},
  {"method":"git","input":{"words":["echo","x",">>","/wt/feature/notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"echo x >> /wt/feature/notes.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"/wt/feature/notes.txt","path":"/wt/feature/notes.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"echo a > /tmp/clone/x.txt; echo b > /private/tmp/claude-501/s/scratchpad/700/n.md; echo c > /Volumes/fast/tmp/clone/y.txt; echo d > /Users/dan/Desktop/n.txt; echo e >> notes.txt"},"want":[["echo","a",">","/tmp/clone/x.txt"],["echo","b",">","/private/tmp/claude-501/s/scratchpad/700/n.md"],["echo","c",">","/Volumes/fast/tmp/clone/y.txt"],["echo","d",">","/Users/dan/Desktop/n.txt"],["echo","e",">>","notes.txt"]]},
  {"method":"git","input":{"words":["echo","a",">","/tmp/clone/x.txt"]},"want":null},
  {"method":"git","input":{"words":["echo","b",">","/private/tmp/claude-501/s/scratchpad/700/n.md"]},"want":null},
  {"method":"git","input":{"words":["echo","c",">","/Volumes/fast/tmp/clone/y.txt"]},"want":null},
  {"method":"git","input":{"words":["echo","d",">","/Users/dan/Desktop/n.txt"]},"want":null},
  {"method":"git","input":{"words":["echo","e",">>","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"echo a > /tmp/clone/x.txt; echo b > /private/tmp/claude-501/s/scratchpad/700/n.md; echo c > /Volumes/fast/tmp/clone/y.txt; echo d > /Users/dan/Desktop/n.txt; echo e >> notes.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"/tmp/clone/x.txt","path":"/tmp/clone/x.txt"},{"word":"/private/tmp/claude-501/s/scratchpad/700/n.md","path":"/private/tmp/claude-501/s/scratchpad/700/n.md"},{"word":"/Volumes/fast/tmp/clone/y.txt","path":"/Volumes/fast/tmp/clone/y.txt"},{"word":"/Users/dan/Desktop/n.txt","path":"/Users/dan/Desktop/n.txt"},{"word":"notes.txt","path":"/repo/notes.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"echo x > /Volumes/locked/notes.txt"},"want":[["echo","x",">","/Volumes/locked/notes.txt"]]},
  {"method":"git","input":{"words":["echo","x",">","/Volumes/locked/notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"echo x > /Volumes/locked/notes.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"/Volumes/locked/notes.txt","path":"/Volumes/locked/notes.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"bash <<'EOF'\necho done >> notes.txt\nEOF"},"want":[["echo","done",">>","notes.txt"]]},
  {"method":"writes","input":{"command":"bash <<'EOF'\necho done >> notes.txt\nEOF","cwd":"/repo","home":""},"want":{"files":[{"word":"notes.txt","path":"/repo/notes.txt"}],"changes":[],"unnamed":[]}},
  {"method":"commands","input":{"command":"truncate -s 0 notes.txt"},"want":[["truncate","-s","0","notes.txt"]]},
  {"method":"git","input":{"words":["truncate","-s","0","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"truncate -s 0 notes.txt","cwd":"/repo","home":""},"want":{"files":[],"changes":[{"word":"notes.txt","path":"/repo/notes.txt","does":"truncate"}],"unnamed":[]}},
  {"method":"commands","input":{"command":"make >& notes.txt"},"want":[["make",">&","notes.txt"]]},
  {"method":"git","input":{"words":["make",">&","notes.txt"]},"want":null},
  {"method":"writes","input":{"command":"make >& notes.txt","cwd":"/repo","home":""},"want":{"files":[{"word":"notes.txt","path":"/repo/notes.txt"}],"changes":[],"unnamed":[]}},
]

const ask = (e: Entry): unknown => {
  const i = e.input as { command: string; cwd: string; home: string; words: string[] }
  const got = e.method === 'commands' ? commands(i.command) : e.method === 'writes' ? commandWrites(i.command, i.cwd, i.home) : git(i.words)
  // As the collision guard receives it: through JSON, nothing standing for no answer.
  return got === undefined ? null : JSON.parse(JSON.stringify(got))
}

describe("the collision guard's table of mod-kit answers", () => {
  test('holds 114 entries', () => {
    expect(ENTRIES.length).toBe(114)
  })
  for (const e of ENTRIES) {
    test(`${e.method} ${JSON.stringify(e.input)}`, () => {
      expect(ask(e)).toEqual(e.want)
    })
  }
})
