#!/usr/bin/env python3
"""kit-table.py: hold the collision guard's table of mod-kit answers to mod-kit's own reader (#760 item 7).

    python3 tools/kit-table.py <repo root>            write the mod-kit test from the table
    python3 tools/kit-table.py <repo root> --check    exit 1 when the written test is not current

The collision guard's tests answer every `$.modkit` call from a table (`KIT` in
payload/mods/collision-guard/tests/register.test.ts), each answer measured from mod-kit's reader when
it was written. A later change to the reader leaves those tests green against answers it no longer
gives (L52, L41). A mod's test cannot import another mod's files, so this carries the table into
mod-kit's own tests as payload/mods/mod-kit/tests/kit-table.test.ts, where each entry is asked of the
real reader and compared: a reader change that moves an answer fails there, by entry. The file is
generated, so --check (run by tools/test-kit-table.sh in every suite run) fails when the table and
the generated test disagree (L422).

Exit codes: 0 written or current; 1 not current (--check); 2 usage, or a table that cannot be read.
"""

import json
import os
import sys

TABLE = 'payload/mods/collision-guard/tests/register.test.ts'
OUT = 'payload/mods/mod-kit/tests/kit-table.test.ts'
METHODS = {'commands', 'writes', 'git'}


def entries(text):
    start = text.find('const KIT = new Map<string, unknown>([')
    if start < 0:
        raise ValueError('no `const KIT = new Map<string, unknown>([` in the table file')
    end = text.find('\n])', start)
    if end < 0:
        raise ValueError('the KIT table never closes')
    out = []
    dec = json.JSONDecoder()
    for n, line in enumerate(text[start:end].split('\n')[1:], 1):
        s = line.strip()
        if not s or s.startswith('//'):
            continue
        if not s.startswith('['):
            raise ValueError(f'KIT line {n} is not an entry: {s[:60]}')
        key, at = dec.raw_decode(s, 1)
        rest = s[at:].lstrip()
        if not rest.startswith(','):
            raise ValueError(f'KIT line {n} has no value after its key')
        value, _ = dec.raw_decode(rest[1:].lstrip())
        method, _, arg = key.partition(' ')
        if method not in METHODS:
            raise ValueError(f'KIT line {n} asks an unknown reader: {method}')
        out.append({'method': method, 'input': json.loads(arg), 'want': value})
    if not out:
        raise ValueError('the KIT table is empty')
    return out


def render(es):
    rows = ',\n'.join('  ' + json.dumps(e, separators=(',', ':')) for e in es)
    return f"""// GENERATED by tools/kit-table.py from {TABLE}: do not edit; run the tool.
//
// Every answer the collision guard's tests take from their table of mod-kit answers, asked of
// mod-kit's real reader (#760 item 7). An entry failing here means the reader has moved and the
// collision guard's tests are green against an answer it no longer gives: re-measure that entry
// in the table, then run the tool again.
import {{ describe, expect, test }} from 'claude-code/testing'
import {{ commands, git }} from '../hooks/commands.ts'
import {{ commandWrites }} from '../hooks/writes.ts'

type Entry = {{ method: 'commands' | 'writes' | 'git'; input: Record<string, unknown>; want: unknown }}
const ENTRIES: Entry[] = [
{rows},
]

const ask = (e: Entry): unknown => {{
  const i = e.input as {{ command: string; cwd: string; home: string; words: string[] }}
  const got = e.method === 'commands' ? commands(i.command) : e.method === 'writes' ? commandWrites(i.command, i.cwd, i.home) : git(i.words)
  // As the collision guard receives it: through JSON, nothing standing for no answer.
  return got === undefined ? null : JSON.parse(JSON.stringify(got))
}}

describe("the collision guard's table of mod-kit answers", () => {{
  test('holds {len(es)} entries', () => {{
    expect(ENTRIES.length).toBe({len(es)})
  }})
  for (const e of ENTRIES) {{
    test(`${{e.method}} ${{JSON.stringify(e.input)}}`, () => {{
      expect(ask(e)).toEqual(e.want)
    }})
  }}
}})
"""


def main(argv):
    if len(argv) not in (2, 3) or (len(argv) == 3 and argv[2] != '--check'):
        print('Usage: kit-table.py <repo root> [--check]', file=sys.stderr)
        return 2
    root = argv[1]
    try:
        with open(os.path.join(root, TABLE), encoding='utf-8') as f:
            es = entries(f.read())
    except (OSError, ValueError) as e:
        print(f'kit-table: cannot read the table: {e}', file=sys.stderr)
        return 2
    want = render(es)
    out = os.path.join(root, OUT)
    if len(argv) == 3:
        try:
            with open(out, encoding='utf-8') as f:
                have = f.read()
        except OSError:
            have = None
        if have != want:
            print(f'kit-table: {OUT} is not current with the table in {TABLE}. Run: python3 tools/kit-table.py .', file=sys.stderr)
            return 1
        print(f'kit-table: {OUT} is current ({len(es)} entries)')
        return 0
    tmp = out + '.tmp'
    with open(tmp, 'w', encoding='utf-8') as f:
        f.write(want)
    os.replace(tmp, out)
    print(f'kit-table: wrote {OUT} ({len(es)} entries)')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
